import { compileClip, sampleClip, validateClip } from '../../src/animation/AnimationClip.js';

export const ROLES = Object.freeze(['attacker', 'defender']);
export const EASES = Object.freeze(['linear', 'easeIn', 'easeOut', 'easeInOut', 'step']);
export const POSE_CHANNELS = Object.freeze([
    'lArm', 'rArm', 'lElbow', 'rElbow',
    'lLeg', 'rLeg', 'lKnee', 'rKnee',
    'lean', 'crouch',
]);

const round = value => Math.round(value * 10000) / 10000;
const clone = value => JSON.parse(JSON.stringify(value));

export function basePose() {
    return {
        lArm: 0, rArm: 0, lElbow: 0.7, rElbow: 0.7,
        lLeg: -0.08, rLeg: 0.08, lKnee: 0.22, rKnee: 0.22,
        lean: 0, crouch: 0,
    };
}

export function createDraft(id = 'untitled_move', duration = 1.2) {
    const pose = basePose();
    return {
        id,
        duration,
        tracks: Object.fromEntries(ROLES.map(role => [role, {
            keyframes: [{ at: 0, ease: 'linear', pose: { ...pose }, transform: { x: 0, y: 0 }, parts: {} }],
        }])),
        events: [],
    };
}

export function normalizeDraft(source) {
    const draft = clone(source ?? createDraft());
    draft.id ||= 'untitled_move';
    draft.duration = Math.max(0.05, Number(draft.duration) || 1.2);
    draft.tracks ||= {};
    for (const role of ROLES) {
        const track = draft.tracks[role] ??= { keyframes: [] };
        if (!track.keyframes.length) {
            track.keyframes.push({ at: 0, ease: 'linear', pose: basePose(), transform: { x: 0, y: 0 }, parts: {} });
        }
        for (const frame of track.keyframes) {
            frame.at = Math.max(0, Math.min(draft.duration, Number(frame.at) || 0));
            frame.ease = EASES.includes(frame.ease) ? frame.ease : 'linear';
            frame.pose ||= {};
            frame.transform ||= {};
            frame.parts ||= {};
        }
        track.keyframes.sort((a, b) => a.at - b.at);
    }
    draft.events = (draft.events ?? []).map(event => ({
        at: Math.max(0, Math.min(draft.duration, Number(event.at) || 0)),
        type: String(event.type || 'marker'),
    })).sort((a, b) => a.at - b.at);
    return draft;
}

export function insertKeyframe(draft, role, at, state) {
    const track = draft.tracks[role];
    if (!track) throw new Error(`Unknown role ${role}`);
    const time = Math.max(0, Math.min(draft.duration, round(at)));
    const existing = track.keyframes.findIndex(frame => Math.abs(frame.at - time) < 0.0001);
    const frame = {
        at: time,
        ease: state.ease ?? 'linear',
        pose: clone(state.pose ?? {}),
        transform: clone(state.transform ?? {}),
        parts: clone(state.parts ?? {}),
    };
    if (existing >= 0) track.keyframes[existing] = frame;
    else track.keyframes.push(frame);
    track.keyframes.sort((a, b) => a.at - b.at);
    return track.keyframes.indexOf(frame);
}

export function removeKeyframe(draft, role, index) {
    const frames = draft.tracks[role]?.keyframes;
    if (!frames || frames.length <= 1) return false;
    frames.splice(index, 1);
    return true;
}

export function addEvent(draft, at, type) {
    draft.events.push({ at: round(Math.max(0, Math.min(draft.duration, at))), type: type || 'marker' });
    draft.events.sort((a, b) => a.at - b.at);
}

export function sampleDraft(draft, at) {
    return sampleClip(compileClip(normalizeDraft(draft)), at);
}

export function draftValidation(draft) {
    return validateClip(normalizeDraft(draft));
}

function jsValue(value, indent = 0) {
    const space = ' '.repeat(indent);
    if (Array.isArray(value)) {
        if (!value.length) return '[]';
        return `[\n${value.map(item => `${' '.repeat(indent + 4)}${jsValue(item, indent + 4)}`).join(',\n')}\n${space}]`;
    }
    if (value && typeof value === 'object') {
        const entries = Object.entries(value);
        if (!entries.length) return '{}';
        return `{\n${entries.map(([key, item]) => `${' '.repeat(indent + 4)}${key}: ${jsValue(item, indent + 4)}`).join(',\n')}\n${space}}`;
    }
    if (typeof value === 'string') return JSON.stringify(value);
    return String(value);
}

export function exportModule(draft) {
    const normalized = normalizeDraft(draft);
    const symbol = normalized.id.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^[^a-zA-Z_$]/, '_$&');
    return `// Generated by tools/move-editor. Review event handling in the move executor.\nexport const ${symbol}Clip = ${jsValue(normalized)};\n`;
}

export function variantChoices(character, slot) {
    const variants = character?.textures?.variants ?? {};
    const families = {
        nearUpperArm: 'upperArm', farUpperArm: 'upperArm',
        nearForearm: 'forearm', farForearm: 'forearm',
        nearHand: 'hand', farHand: 'hand',
        nearThigh: 'thigh', farThigh: 'thigh',
        nearShin: 'shin', farShin: 'shin',
        nearBoot: 'boot', farBoot: 'boot',
    };
    return ['base', ...new Set([
        ...Object.keys(variants[families[slot]] ?? {}),
        ...Object.keys(variants[slot] ?? {}),
    ])];
}
