// Hammerlock — the first PAIRED move on the seekable clip runtime (see
// RIG_AND_MOVE_PIPELINE.md's "Migration order" step 2), and the first move
// authored END TO END in tools/move-editor with a grip that is actually made:
// the attacker's gripping wrist sits on the defender's trapped wrist for the
// whole hold, measured, not implied.
//
// WHERE THE PIECES LIVE, and why they are split:
//
//   ./hammerlock.tracks.js  the choreography. GENERATED by
//                           tools/move-editor/author_hammerlock.mjs, because it
//                           is solved geometry — the output of the editor's
//                           two-bone solve driving both arms onto one point —
//                           not stances anyone picked. Writing it out as named
//                           constants would dress derived data up as authored
//                           data.
//   this file               every DECISION: duration, phase times, markers,
//                           the staging tableau, and the reasoning. A human
//                           owns these; the solver owns the joint angles.
//   tools/move-editor/drafts/hammerlock.json
//                           the authoring artifact the two are generated from,
//                           carrying what the clip must never see (the declared
//                           contact interval, the posture, the preview facing).
//
// tests/hammerlockAuthoring.test.js holds all three in agreement by semantic
// comparison, and npm run proof:hammerlock measures the result on the live
// runtime and both rendered skeletons.
//
// Gameplay (Wrestler._doHammerlock's event handlers) still owns damage,
// stamina, state, and the character-specific recovery.

import { HAMMERLOCK_TRACKS } from './hammerlock.tracks.js';

// Legacy timing this clip reproduces 1:1 (MOVE_DEFS.hammerlock.poseSeq, in ms,
// each step's duration is the tween INTO that pose from the previous one):
//   reach 120  ->  turn 180  ->  set 200  ->  crank 900   (1400ms of hold)
// Cumulative phase boundaries: reach done @120, turn @300, set @500, crank @1400.
// The two old delayedCalls — drain at 300ms, release (+drain) at 1400ms — became
// the apply-drain and release-contact markers below, at the same times, so the
// feel and the damage schedule are unchanged. The 220ms settle back to each
// character's CONFIGURED idle pose is owned by the executor (onComplete), not
// this shared clip data — the idle target differs per wrestler (Lou's theszIdle
// vs George's powerIdle) and must never be baked into a shared clip.
const REACH_AT   = 0.120;
const TURN_AT    = 0.300;
const SET_AT     = 0.500;
export const HAMMERLOCK_DURATION       = 1.400;
export const HAMMERLOCK_CONTACT_AT     = REACH_AT; // hand catches the wrist
export const HAMMERLOCK_DRAIN_AT       = TURN_AT; // first crank drain lands as the set begins
export const HAMMERLOCK_RELEASE_AT     = HAMMERLOCK_DURATION;
export const HAMMERLOCK_DEF_SET_AT     = 0.260;   // defender fully into the trapped stance
export const HAMMERLOCK_CLIP_ID        = 'hammerlock';

// ── The grip ─────────────────────────────────────────────────────────────────
//
// The attacker's gripping wrist holds the defender's trapped wrist from the
// catch to the release. This is DECLARED in the draft as a required contact and
// MEASURED: worst separation 0.11 px across 115 graded frames on the reference
// rig, which is what makes it a hold rather than a silhouette that suggests one.
//
// It did not start that way. The shipped choreography's two wrists never came
// within 155 px in game (284 px in the editor) against a 93–160 px arm reach —
// no pose of that arm could have closed it. Three things had to change, each
// measured rather than guessed:
//
//   1. The approach lands ON the catch (HAMMERLOCK_STAGING below), not 140 ms
//      after it. You cannot catch a wrist that is still closing 70 rig units.
//   2. Both wrestlers PLANT for the hold. The torso origin is solved from both
//      hip sockets, so the legacy stance-to-stance leg swing moved the torso,
//      the shoulder, and therefore the gripping arm: 0.015 rad of far hip moves
//      the near elbow 9.98 px on the reference rig. The grip is exact at every
//      keyframe, so that motion reappeared as a bulge between them and no
//      amount of extra keyframes helped — the travel was the cause. A working
//      hammerlock is cranked from a braced base anyway.
//   3. The trapped wrist travels a smooth path up the back rather than a
//      hand-picked one; a two-bone solve resolves its redundancy from wherever
//      the arm currently is, so a kinked target path makes consecutive
//      keyframes land on different branches and the line between them bulges.
export const HAMMERLOCK_GRIP = Object.freeze({
    from: REACH_AT,
    to: HAMMERLOCK_DURATION,
    role: 'attacker',
    source: 'nearWrist',
    target: 'nearWrist',
});

// ── Staging: the authored tableau ────────────────────────────────────────────
//
// Rig units from the SHARED tableau origin — the attacker's position when the
// clip begins (src/animation/clipStaging.js). These are not new choreography:
// they are the ring geometry Wrestler._doHammerlock used to build imperatively
// with two Phaser tweens (`sx + facing*30*s` for the defender, 24 units back
// from that for the attacker), moved into clip data so the move editor can
// compose, preview and re-measure the tableau instead of an author having to
// read it out of gameplay code.
//
// The entry offsets are load-bearing under the shared-origin contract: at t=0
// each actor is PLACED there. They are the real trigger geometry, not a guess —
// hammerlock can only be committed from inside a lockup, and Arena._tickLockup
// holds that tie-up at a gap of exactly 100*s with both wrestlers on one depth
// line. Measured on the live game across three commitments: 99.539 rig units
// (the residue is the lockup's exponential approach), so the t=0 placement
// moves the defender under half a rig unit and the attacker not at all.
//
// The approach now COMPLETES at the catch (REACH_AT) rather than at 0.26, so
// the tableau is stationary for the whole held window. That is what lets the
// grip hold: two bodies still travelling through each other cannot keep a
// contact that is only exact at its keyframes.
//
// Two behavioural changes versus the old executor tweens, both deliberate: the
// defender is pulled onto the attacker's depth line rather than keeping
// whatever depth it committed at (a paired hold is one rigid tableau), and the
// approach takes 120 ms instead of 300 ms.
export const HAMMERLOCK_STAGING = Object.freeze({
    attackerEntry:  Object.freeze({ x: 0,   y: 0 }),
    defenderEntry:  Object.freeze({ x: 100, y: 0 }),
    attackerWork:   Object.freeze({ x: 6,   y: 0 }),
    defenderWork:   Object.freeze({ x: 30,  y: 0 }),
    arrivalAt:      REACH_AT,
});

// The attacker's gripping hand wears `grip` art for exactly the length of the
// hold: acquired on the catch and returned to base on the release frame.
// `workingHand` is a SEMANTIC slot, not a fixed near/far one —
// src/rig/partVariants.js maps it to the hand on the arm the pose drives as
// lArm, which the skeleton renders as the near hand facing right and the far
// hand facing left, so the grip lands on the correct hand in BOTH facings.
// Characters that publish no `hand` variant family resolve it to their
// calibrated base hand art, so this is a safe no-op on George and Lou and a
// real swap on the reference rig — which is what the editor previews against.
export const hammerlockClip = {
    id: HAMMERLOCK_CLIP_ID,
    duration: HAMMERLOCK_DURATION,
    // Two roles sampled at the same clip time every frame — the paired proof.
    tracks: HAMMERLOCK_TRACKS,
    events: [
        // Hand catches the wrist — and now actually catches it. (It sits at the
        // reach, not 0: eventsBetween is (from, to], so an at=0 marker could
        // never emit, and the physical grab is already owned synchronously by
        // the executor's holding-state assignment at commitment.)
        { at: HAMMERLOCK_CONTACT_AT, type: 'acquire-contact' },
        // First crank drain, as the set begins (was delayedCall(300)).
        { at: HAMMERLOCK_DRAIN_AT,  type: 'apply-drain' },
        // Release drain + hand-off back to standing (was delayedCall(1400)).
        // eventsBetween is (from, to] and `to` reaches duration on the final
        // step, so this fires exactly once on natural completion and never when
        // a preview merely seeks. A move cancelled before 1.4s never reaches it,
        // so an interrupted hammerlock correctly deals no release damage.
        { at: HAMMERLOCK_RELEASE_AT, type: 'release-contact' },
    ],
};

// Named seek targets for the preview/test seam (tools/debug/hammerlock_preview.mjs
// and tests) so entry / contact-set / crank / release / recovery can each be
// inspected at an exact, deterministic time without live gameplay.
export const HAMMERLOCK_PHASES = Object.freeze({
    entry:    0.0,                    // tie-up, before the reach
    reach:    REACH_AT,               // hand catches the wrist (contact frame)
    turn:     TURN_AT,
    set:      SET_AT,                 // arm folded, first drain frame
    crank:    (SET_AT + HAMMERLOCK_DURATION) / 2, // deep in the working hold
    release:  HAMMERLOCK_DURATION,    // release frame
});
